apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxyt.fullname" . }}
  labels:
    {{- include "proxyt.labels" . | nindent 4 }}
data:
  PROXYT_DOMAIN: {{ .Values.proxyt.domain | quote }}
  PROXYT_HTTP_ONLY: {{ .Values.proxyt.httpOnly | quote }}
  PROXYT_DEBUG: {{ .Values.proxyt.debug | quote }}
  PROXYT_CERT_DIR: {{ .Values.proxyt.certDir | quote }}
  PROXYT_ISSUE: {{ .Values.proxyt.issue | quote }}
  PROXYT_PORT: {{ .Values.proxyt.port | quote }}
  PROXYT_HTTPS_PORT: {{ .Values.proxyt.httpsPort | quote }}
  PROXYT_BIND: {{ .Values.proxyt.bind | quote }}

