{{- if and .Values.proxyt.email (not .Values.proxyt.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxyt.fullname" . }}
  labels:
    {{- include "proxyt.labels" . | nindent 4 }}
type: Opaque
stringData:
  email: {{ .Values.proxyt.email | quote }}
{{- end }}

