apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxyt.fullname" . }}
  labels:
    {{- include "proxyt.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol }}
      name: http
    {{- if not .Values.proxyt.httpOnly }}
    - port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: {{ .Values.service.ports.https.protocol }}
      name: https
    {{- end }}
  selector:
    {{- include "proxyt.selectorLabels" . | nindent 4 }}
